# CMAKE generated file: DO NOT EDIT!
# Generated by "MSYS Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/c/Program Files (x86)/CMake 2.8/bin/cmake.exe"

# The command to remove a file.
RM = "/c/Program Files (x86)/CMake 2.8/bin/cmake.exe" -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/c/Program Files (x86)/CMake 2.8/bin/cmake-gui.exe"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /C/cproject/RunOver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /C/cproject/RunOver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/c/Program Files (x86)/CMake 2.8/bin/cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"/c/Program Files (x86)/CMake 2.8/bin/cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"/c/Program Files (x86)/CMake 2.8/bin/cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"/c/Program Files (x86)/CMake 2.8/bin/cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"/c/Program Files (x86)/CMake 2.8/bin/cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/c/Program Files (x86)/CMake 2.8/bin/cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /C/cproject/RunOver/CMakeFiles /C/cproject/RunOver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /C/cproject/RunOver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named base

# Build rule for target.
base: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 base
.PHONY : base

# fast build rule for target.
base/fast:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/build
.PHONY : base/fast

#=============================================================================
# Target rules for targets named runover

# Build rule for target.
runover: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runover
.PHONY : runover

# fast build rule for target.
runover/fast:
	$(MAKE) -f CMakeFiles/runover.dir/build.make CMakeFiles/runover.dir/build
.PHONY : runover/fast

src/engine/Angle.obj: src/engine/Angle.cpp.obj
.PHONY : src/engine/Angle.obj

# target to build an object file
src/engine/Angle.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/engine/Angle.cpp.obj
.PHONY : src/engine/Angle.cpp.obj

src/engine/Angle.i: src/engine/Angle.cpp.i
.PHONY : src/engine/Angle.i

# target to preprocess a source file
src/engine/Angle.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/engine/Angle.cpp.i
.PHONY : src/engine/Angle.cpp.i

src/engine/Angle.s: src/engine/Angle.cpp.s
.PHONY : src/engine/Angle.s

# target to generate assembly for a file
src/engine/Angle.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/engine/Angle.cpp.s
.PHONY : src/engine/Angle.cpp.s

src/engine/KeyBuffer.obj: src/engine/KeyBuffer.cpp.obj
.PHONY : src/engine/KeyBuffer.obj

# target to build an object file
src/engine/KeyBuffer.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/engine/KeyBuffer.cpp.obj
.PHONY : src/engine/KeyBuffer.cpp.obj

src/engine/KeyBuffer.i: src/engine/KeyBuffer.cpp.i
.PHONY : src/engine/KeyBuffer.i

# target to preprocess a source file
src/engine/KeyBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/engine/KeyBuffer.cpp.i
.PHONY : src/engine/KeyBuffer.cpp.i

src/engine/KeyBuffer.s: src/engine/KeyBuffer.cpp.s
.PHONY : src/engine/KeyBuffer.s

# target to generate assembly for a file
src/engine/KeyBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/engine/KeyBuffer.cpp.s
.PHONY : src/engine/KeyBuffer.cpp.s

src/engine/Scene.obj: src/engine/Scene.cpp.obj
.PHONY : src/engine/Scene.obj

# target to build an object file
src/engine/Scene.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/engine/Scene.cpp.obj
.PHONY : src/engine/Scene.cpp.obj

src/engine/Scene.i: src/engine/Scene.cpp.i
.PHONY : src/engine/Scene.i

# target to preprocess a source file
src/engine/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/engine/Scene.cpp.i
.PHONY : src/engine/Scene.cpp.i

src/engine/Scene.s: src/engine/Scene.cpp.s
.PHONY : src/engine/Scene.s

# target to generate assembly for a file
src/engine/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/engine/Scene.cpp.s
.PHONY : src/engine/Scene.cpp.s

src/engine/VoidReceiver.obj: src/engine/VoidReceiver.cpp.obj
.PHONY : src/engine/VoidReceiver.obj

# target to build an object file
src/engine/VoidReceiver.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/engine/VoidReceiver.cpp.obj
.PHONY : src/engine/VoidReceiver.cpp.obj

src/engine/VoidReceiver.i: src/engine/VoidReceiver.cpp.i
.PHONY : src/engine/VoidReceiver.i

# target to preprocess a source file
src/engine/VoidReceiver.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/engine/VoidReceiver.cpp.i
.PHONY : src/engine/VoidReceiver.cpp.i

src/engine/VoidReceiver.s: src/engine/VoidReceiver.cpp.s
.PHONY : src/engine/VoidReceiver.s

# target to generate assembly for a file
src/engine/VoidReceiver.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/engine/VoidReceiver.cpp.s
.PHONY : src/engine/VoidReceiver.cpp.s

src/engine/World.obj: src/engine/World.cpp.obj
.PHONY : src/engine/World.obj

# target to build an object file
src/engine/World.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/engine/World.cpp.obj
.PHONY : src/engine/World.cpp.obj

src/engine/World.i: src/engine/World.cpp.i
.PHONY : src/engine/World.i

# target to preprocess a source file
src/engine/World.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/engine/World.cpp.i
.PHONY : src/engine/World.cpp.i

src/engine/World.s: src/engine/World.cpp.s
.PHONY : src/engine/World.s

# target to generate assembly for a file
src/engine/World.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/engine/World.cpp.s
.PHONY : src/engine/World.cpp.s

src/game/Character.obj: src/game/Character.cpp.obj
.PHONY : src/game/Character.obj

# target to build an object file
src/game/Character.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/game/Character.cpp.obj
.PHONY : src/game/Character.cpp.obj

src/game/Character.i: src/game/Character.cpp.i
.PHONY : src/game/Character.i

# target to preprocess a source file
src/game/Character.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/game/Character.cpp.i
.PHONY : src/game/Character.cpp.i

src/game/Character.s: src/game/Character.cpp.s
.PHONY : src/game/Character.s

# target to generate assembly for a file
src/game/Character.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/game/Character.cpp.s
.PHONY : src/game/Character.cpp.s

src/game/scene/GameScene.obj: src/game/scene/GameScene.cpp.obj
.PHONY : src/game/scene/GameScene.obj

# target to build an object file
src/game/scene/GameScene.cpp.obj:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/game/scene/GameScene.cpp.obj
.PHONY : src/game/scene/GameScene.cpp.obj

src/game/scene/GameScene.i: src/game/scene/GameScene.cpp.i
.PHONY : src/game/scene/GameScene.i

# target to preprocess a source file
src/game/scene/GameScene.cpp.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/game/scene/GameScene.cpp.i
.PHONY : src/game/scene/GameScene.cpp.i

src/game/scene/GameScene.s: src/game/scene/GameScene.cpp.s
.PHONY : src/game/scene/GameScene.s

# target to generate assembly for a file
src/game/scene/GameScene.cpp.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/game/scene/GameScene.cpp.s
.PHONY : src/game/scene/GameScene.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) -f CMakeFiles/runover.dir/build.make CMakeFiles/runover.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/runover.dir/build.make CMakeFiles/runover.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/runover.dir/build.make CMakeFiles/runover.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... base"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... runover"
	@echo "... src/engine/Angle.obj"
	@echo "... src/engine/Angle.i"
	@echo "... src/engine/Angle.s"
	@echo "... src/engine/KeyBuffer.obj"
	@echo "... src/engine/KeyBuffer.i"
	@echo "... src/engine/KeyBuffer.s"
	@echo "... src/engine/Scene.obj"
	@echo "... src/engine/Scene.i"
	@echo "... src/engine/Scene.s"
	@echo "... src/engine/VoidReceiver.obj"
	@echo "... src/engine/VoidReceiver.i"
	@echo "... src/engine/VoidReceiver.s"
	@echo "... src/engine/World.obj"
	@echo "... src/engine/World.i"
	@echo "... src/engine/World.s"
	@echo "... src/game/Character.obj"
	@echo "... src/game/Character.i"
	@echo "... src/game/Character.s"
	@echo "... src/game/scene/GameScene.obj"
	@echo "... src/game/scene/GameScene.i"
	@echo "... src/game/scene/GameScene.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

